### ISSUE TITLE
Security Issue (gmail)

### ISSUE THREAD

**Issue by ousamabenyounes** [tgallin/accompagnerlautisme#1]
accompagnerlautisme/config/secrets.js  has been compromised and your login/pwd are now visible on this project
to remove it from your history:
https://help.github.com/articles/removing-sensitive-data-from-a-repository/

Change your login/pwd on all your projects...

Hope this will help you :)

**Comment by ousamabenyounes** [comment]
accompagnerlautisme is a nice project and I'll be happy to give your more help on this if you need!

**Comment by tgallin** [comment]
Thanks a lot for your feedback. I'll take time to remove the secrets.js file from the git history and I'll change my login/pwd on my projects.

**Comment by tgallin** [comment]
It should be good now :) Thanks again
